SinatraでシンプルなWebアプリを作ろうの課題の提出
ReiyaPr/public pull request #1
Opened 2021-05-27 15:49 UTC by ReiyaPr

メモアプリを作成しました
今までで一番苦労したかもしれないです..

2021-05-31 06:45 UTC, komagata requested changes

2021-05-31 06:45 UTC, komagata commented on Gemfile
> +gem 'sinatra-contrib'
最終行に改行がないようです〜

2021-05-31 06:45 UTC, komagata commented on memo.rb
> +def read_json_file
メソッドにしてるのいいですね！

2021-05-31 06:45 UTC, komagata commented on memo.rb
> +  redirect to('')
```suggestion
  redirect to('')
```

こっちの方が明示的でいいかもです〜

2021-05-31 06:45 UTC, komagata commented on memo.rb
> +delete '/memos/:id/edit' do
`delete`と`edit`があると、削除なのか編集なのかわからないので他のURLにした方がいいかもです〜

2021-05-31 06:45 UTC, komagata commented on public/css/style.css
> +
最終行に改行がないようです〜

2021-05-31 06:45 UTC, komagata commented on views/detail.erb
> +
不要な空行があるみたいです

2021-05-31 15:59 UTC, ReiyaPr commented on Gemfile
> +gem 'sinatra-contrib'
改行追加しました〜

2021-05-31 15:59 UTC, ReiyaPr commented on memo.rb
> +  redirect to('')
redirect to('/')に修正しました。こちらの方が明示的という理解であってますか？

2021-05-31 16:00 UTC, ReiyaPr commented on memo.rb
> +delete '/memos/:id/edit' do
URIをmemos/:idに修正しました。それに合わせて、PATCHメソッドのURIもmemos/:idに修正しました！

2021-05-31 16:00 UTC, ReiyaPr commented on public/css/style.css
> +
改行加えました〜

2021-05-31 16:01 UTC, ReiyaPr commented on views/detail.erb
> +
空行を削除しました〜

2021-06-01 05:50 UTC, komagata commented on memo.rb
> +  redirect to('')
はい、そうです〜

2021-06-01 05:53 UTC, komagata requested changes

2021-06-01 05:53 UTC, komagata commented on views/home.erb
> +
不要な空行があるようです〜

指摘点以外も他にも不要な空行がないか全部の変更ファイルを見直してみてください〜

2021-06-01 05:53 UTC, komagata commented on views/edit.erb
> +</head>
ここはlayoutファイルに書くべき内容かも？

2021-06-01 12:14 UTC, ReiyaPr commented on views/home.erb
> +
一度全ファイルを見直して、空行見直しました
git diffをもっと活用するべきでした...

2021-06-01 12:23 UTC, ReiyaPr commented on views/edit.erb
> +</head>
edit.erbから削除し、layout.erbで読み込まれるように設定しました
初め`href=../css/style.css`でlayout.erbに統一していたのですが、edit.erbに設定した`href=/css/style.css`が正しいアドレス表記でした

2021-06-02 03:40 UTC, komagata requested changes

2021-06-02 03:40 UTC, komagata commented on views/layout.erb
> +<a class="header" href="/">MEMO</a>
htmlではheadとbody要素の間には何も入れちゃダメなはずです。
aなどの要素はbodyの中に書くようにお願いします〜

2021-06-02 03:40 UTC, komagata commented on views/layout.erb
> +<footer>Reiya@2021</footer>
こちらもbodyの中に入れてください〜

2021-06-02 15:19 UTC, ReiyaPr commented on views/layout.erb
> +<a class="header" href="/">MEMO</a>
aタグの要素をbodyの中に移動しました〜

2021-06-02 15:20 UTC, ReiyaPr commented on views/layout.erb
> +<footer>Reiya@2021</footer>
footerタグもbodyの中に移動しました〜

2021-06-04 11:53 UTC, komagata requested changes

2021-06-04 11:53 UTC, komagata commented on public/css/style.css
> +
不要な空行があるようです〜

2021-06-05 03:03 UTC, ReiyaPr commented on public/css/style.css
> +
空行削除しました〜

2021-06-05 12:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-06 05:09 UTC, merged